apiVersion: batch/v1
kind: Job
metadata:
  name: af-db-initializer-job
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: af-db-initializer
        image: 207385250759.dkr.ecr.us-east-2.amazonaws.com/af-db-initializer:latest
        volumeMounts:
          - name: db-connection
            mountPath: /etc/secret-volume/mongo-secrets/db-connection
          - name: mongo-users
            mountPath: /etc/secret-volume/mongo-secrets/users
          - name: superuser-db-credentials
            mountPath: /etc/secret-volume/mongo-secrets/users/superuser-db-credentials
      volumes:
        - name: db-connection
          secret:
            secretName: db-connection 
        - name: superuser-db-credentials
          secret: 
            secretName: superuser-db-credentials
        - name: mongo-users
          projected:
            sources:
              - secret:
                  name: auth-app-db-credentials
              - secret:
                  name: account-app-db-credentials 