apiVersion: batch/v1
kind: Job
metadata:
  name: af-db-initializer-job
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: af-db-initializer
        image: 207385250759.dkr.ecr.us-east-2.amazonaws.com/af-db-initializer:latest
        volumeMounts:
          - name: db-connection
            mountPath: /etc/secret-volume/mongo-secrets/db-connection
          - name: superuser-db-credentials
            mountPath: /etc/secret-volume/mongo-secrets/users/super-user-db-credentials
          - name: auth-app-db-credentials
            mountPath: /etc/secret-volume/mongo-secrets/users/auth-app-db-credentials
          - name: account-app-db-credentials
            mountPath: /etc/secret-volume/mongo-secrets/users/account-app-db-credentials
      volumes:
        - name: db-connection
          secret:
            secretName: db-connection 
        - name: superuser-db-credentials
          secret: 
            secretName: superuser-db-credentials
        - name: auth-app-db-credentials
          secret:
            secretName: auth-app-db-credentials
        - name: account-app-db-credentials
          secret:
            secretName: account-app-db-credentials